### ISSUE TITLE
[BUG] RSA Generator doesn't work in Docker

### ISSUE THREAD

**Issue by cdn4lf** [CorentinTh/it-tools#287] opened 2023-03-26 16:08 UTC
**Describe the bug**
RSA Generator doesn't work when self-hosted in Docker

**To Reproduce**
Deploy docker container
Attempt to create RSA Key
- This works correctly on Web hosted version

**Expected behavior**

**Screenshots**
2023/03/25 23:59:28 [error] 30#30: *9 open() "/usr/share/nginx/html/forge/prime.worker.js" failed (2: No such file or directory), client: 192.168.18.120, server: localhost, request: "GET /forge/prime.worker.js HTTP/1.1", host: "192.168.xxx.xxx:5545", referrer: "http://192.168.xxx.xxx:5545/rsa-key-pair-generator"

**Additional context**

**Comment by CorentinTh** [comment] 2023-03-26 20:21
Hi @cdn4lf 
Thank you for reporting this bug

Do you have more info, I'm unable to reproduce what your saying
Is your docker image up to date ?

![image](https://user-images.githubusercontent.com/25065347/227802340-6310c39d-8aab-47a7-b16b-aa17390af787.png)

**Comment by cdn4lf** [comment] 2023-03-26 20:30
I'm using the latest image.  Running on a Linux (Ubuntu) box.

![Screenshot_20230326_162935_Chrome](https://user-images.githubusercontent.com/49874417/227802917-dcf1795e-af64-49fd-b18f-21f8ff8c0122.jpg)

**Comment by andriibratanin** [comment] 2023-03-26 21:15
+1, I have the same issue in Docker

**Comment by CorentinTh** [comment] 2023-03-26 22:40
Ok so the problem is that node-forge try **sometimes** to fetch a web worker on some machine to compute prime numbers

It's normally fixed in #290
Can you please try if everything is ok since I cannot reproduce the bug ?

**Comment by nickm324** [comment] 2023-03-26 22:54
I have this issue also, running fresh and update version of docker, latest image.

**Comment by CorentinTh** [comment] 2023-03-26 22:56
On what hardware a you running ?

**Comment by cdn4lf** [comment] 2023-03-26 22:56
I think I'm running the most recent version, but there's no tags to be certain.  Assuming I am, the fix was not successful.

When I refresh the page, I'm getting an nginx error, which is weird because I'm not running this through nginx.

**Comment by CorentinTh** [comment] 2023-03-26 23:06
What are your client side configurations ?
* which web browser ? version ?
* OS

**Comment by cdn4lf** [comment] 2023-03-28 15:06
This appears to be working for me now.

**Comment by CorentinTh** [comment] 2023-03-28 18:47
Ok, so it's fixed by using the proper prime worker path thanks to #290

**Closed by CorentinTh** 2023-03-28 18:47 UTC
Labels: bug
