### ISSUE TITLE
[BUG]  Incorrect Roman number conversion - Roman to Arabic

### ISSUE THREAD

**Issue by rafaelrodrigues3092** [CorentinTh/it-tools#274] opened 2023-03-24 01:44 UTC
**Describe the bug**
Roman number converter - Conversion from roman to arabic incorrect

**To Reproduce**
1. Go to 'Roman numeral converter'
2. Add 'IVX' to 'Roman to Arabic'
3. You will see '4'. IVX is not valid roman numerical
4. Can be done with other values such as 'IXX' which is also invalid

**Expected behavior**
Correct conversion

**Screenshots**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/40042276/227402552-01f78cc1-dc79-43ab-86d2-08d7dc3af921.png">

**Comment by CorentinTh** [comment] 2023-03-24 12:36
Hi @rafaelrodrigues3092 !
Thank you very much for the report, it's indeed a validation error since IVX is not a valid number, I'll fix it

**Comment by cgoIT** [comment] 2023-04-06 10:11
From my point of view this could be resolved with a simple regex based check with the following regex:

`/^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/`

But: The converter currently only supports numbers up to 3999. I think it's no big deal to add greater numbers (with overlined symbols) in the conversion arabic -> roman. But the problem is the conversion roman -> arabic. At least we need to customize the ui so that you can enter the overlined symbols.

Or just add a hint that only numbers from 1 to 3999 are working... ;)

See: [https://mammothmemory.net/maths/numbers/roman-numerals/roman-numerals-from-1000-to-1-million.html](https://mammothmemory.net/maths/numbers/roman-numerals/roman-numerals-from-1000-to-1-million.html)

**Closed** 2023-04-08 17:33 UTC
Labels: bug
