### ISSUE TITLE
[NEW TOOL] WiFi QR Code Generator

### ISSUE THREAD

**Issue by tweek11** [CorentinTh/it-tools#549] opened 2023-08-05 05:28 UTC
**What tool do you want?**
WiFi QR Code Generator

**Describe the solution you'd like**
To enter in the information for local WiFi and generate a code for guest to scan - This way one does not have to manually hand out a complex password and allows guest to connect easier.

**Is their example of this tool in the wild?**
Yes, these sites currently do the same function. The second site allows to insert a logo in the middle of the QR Code
https://qifi.org/
https://www.qr-code-generator.com/solutions/wifi-qr-code/

**Additional context**
Just discovered this project and absolutely love it. So much easier to than book marking multiple different location for specific task -Thank you kindly.

**Comment by TCB13** [comment] 2023-08-06 11:34
Related and/or duplicate of https://github.com/CorentinTh/it-tools/issues/272 https://github.com/CorentinTh/it-tools/issues/410 https://github.com/CorentinTh/it-tools/issues/275

**Closed** 2023-09-06 07:46 UTC
Labels: new tool

**Comment by ItsNoted** [comment] 2023-09-07 15:31
Awesome! Doesn't look like it has been pushed to "latest" on dockerhub yet. I can use nightly for now or build it myself. Thanks for adding this. I was curious if it can just be combined into the current QR code tool instead of a whole new tool. To keep things more tidy.

Awesome work!

**Comment by TCB13** [comment] 2023-09-07 15:32
@sbordeyne and @CorentinTh thank you :)
