### ISSUE TITLE
[NEW TOOL] RegEx Build and Test

### ISSUE THREAD

**Issue by wuergezwerg** [CorentinTh/it-tools#554] opened 2023-08-09 11:28 UTC
It would be nice to have a "RegEx Build and Test" tool similar to https://regexr.com/. It really helps to create regex when you only need it once every 2 months. The option to look at the different expressions in the cheatsheet helps to remember also :D

**Comment by Nezteb** [comment] 2023-10-04 18:14
Duplicate of https://github.com/CorentinTh/it-tools/issues/308 (which technically came first), though this issue's `[NEW TOOL]` is the correct prefix. 😄

**Comment by sharevb** [comment] 2024-05-05 21:47
Hi @wuergezwerg  and @CorentinTh, implemented in #1030

**Closed** 2024-09-20 18:42 UTC
Labels: new tool
